source 'http://rubygems.org'
gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'

group :development, :test do
  gem 'ruby-debug'
  gem 'rspec-rails'
  gem 'shoulda'

  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
end

gem "hobo", ">= 1.3.0.pre28"
