source 'http://rubygems.org'
gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql'
gem 'devise'
gem 'hobo_devise', '>=0.0.2'
gem 'delayed_job'
gem 'bluecloth'

group :development, :test do
  gem 'ruby-debug'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'email_spec'

  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'show_me_the_cookies'
  gem 'factory_girl_rails'
  gem 'fuubar-cucumber'
end

gem "hobo", ">= 1.3.0.pre28", :git => 'git://github.com/ahenobarbi/hobo.git', :branch => 'rails3'
